<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total Recall)

Purely from memory, write short descriptions of the following terms:

| Term       | Brief Description                                |
| :----------: | :------------------------------------------------: |
| Subsetting | Select elements from arrays or lists             |
| Indexing   | Select ONE element from arrays or lists          |
| Slicing    | Select a SUBSET of elements from arrays or lists |
| Masking    | Only applicable for arrays. Similar to Slicing   |

### Exercise 2 (Show me the 'odd' letters)

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].

<font color='green'> 
    
**Guide**

1. Subset all the first elements.
- You should get array(['1', '3', '2', ..., '10', '9'])
  
2. Convert this to integers using astype(int)
- You must look up how astype() works.
  
3. Use % to get the remainder for division by 2.
- You should get array([1, 1, 0, ..., 0, 1]).
  
4. Use the previous result to create a mask that checks if the remainder is zero or not
- You should get array([True, True, False, ..., False, True]).
  
5. Now you have identified the locations of the odd numbers.
- Use the mask and extract the corresponding second elements.
</font>

In [4]:
np_numbers=np_array_2d[:, 0]
np_numbers

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [5]:
# Astype() will create a new DataFrame where the data types has been changed to the specified type.
np_numbers=np_numbers.astype(int) 
np_numbers
# using .astype() is more useful that int(str) because int(str) can only change one element at a time

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [6]:
np_numbers=np_numbers%2
np_numbers      #odd numbers shows 1 (true)

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [7]:
np_numbers == 1

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [10]:
np_numbers.sum() #not sure whether this is a form of masking, but looks like it works!

5